version: '3.7'

services:

  mongo:
    image: mongo:4.0

  byor-voting-server:
    build: 
      context: .
      target: dev
    image: byor-voting-server
    volumes:
      - byor_backend_app:/usr/src/app
    command: ${BACKEND_COMMAND:-}

volumes:
  byor_backend_app:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind
